version: '3'

services:
  earthworm:
    image: caltechads/earthworm:7.9-build3
    container_name: "earthworm"
    hostname: earthworm
    ipc: private
    volumes:
      - ./etc/ew/params:/eworm/run/params
      - ./data/tanks:/eworm/tankfiles
    environment:
      - SYS_NAME=earthworm.localhost
      - AWS_DEFAULT_REGION=us-west-2
